services:
  postgres:
    image: postgres:15
    container_name: reservas_postgres
    environment:
      POSTGRES_USER: reserva
      POSTGRES_PASSWORD: reserva123
      POSTGRES_DB: reservasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reserva -d reservasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:3.7
    container_name: reservas_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      # --- MODO KRaft (sin Zookeeper) ---
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Puertos internos del modo KRaft
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Seguridad
      ALLOW_PLAINTEXT_LISTENER: "yes"

      # Config extra necesaria para estabilidad
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/bitnami
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 8

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: reservas_kafka_ui
    restart: unless-stopped
    ports:
      - "7777:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

  backend:
    build:
      context: ../backend/src
      dockerfile: Reserva.Api/Dockerfile
    container_name: reservas_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgresConnection: Host=postgres;Port=5432;Database=reservasdb;Username=reserva;Password=reserva123
      Kafka__BootstrapServers: kafka:9092
    ports:
      - "5290:8080"

volumes:
  postgres_data:
  kafka_data:






