version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: reservas_postgres
    environment:
      POSTGRES_USER: reserva
      POSTGRES_PASSWORD: reserva123
      POSTGRES_DB: reservasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reserva"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


