services:
  postgres:
    image: postgres:15
    container_name: reservas_postgres
    environment:
      POSTGRES_USER: reserva
      POSTGRES_PASSWORD: reserva123
      POSTGRES_DB: reservasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reserva -d reservasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend/src
      dockerfile: Reserva.Api/Dockerfile
    container_name: reservas_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgresConnection: Host=postgres;Port=5432;Database=reservasdb;Username=reserva;Password=reserva123
    ports:
      - "5290:8080"
    restart: unless-stopped

volumes:
  postgres_data:



